# permissions for end users to view keycloaks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rhbk-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloak-viewer-role
rules:
- apiGroups:
  - sso.stakater.com
  resources:
  - keycloaks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sso.stakater.com
  resources:
  - keycloaks/status
  verbs:
  - get
