apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: rhbk-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KeycloakImport is the Schema for the keycloakimports API
      displayName: Keycloak Import
      kind: KeycloakImport
      name: keycloakimports.sso.stakater.com
      version: v1alpha1
    - description: Keycloak is the Schema for the keycloaks API
      displayName: Keycloak
      kind: Keycloak
      name: keycloaks.sso.stakater.com
      version: v1alpha1
  description: Go Operator SDK for RHBK
  displayName: Stakater RHBK Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - RHBK
  - Keycloak
  - Red Hat
  - Stakater
  links:
  - name: Rhbk Operator
    url: https://rhbk-operator.domain
  maturity: alpha
  provider:
    name: Stakater
    url: stakater.com
  version: 0.0.0
