apiVersion: sso.stakater.com/v1alpha1
kind: Keycloak
metadata:
  labels:
    app.kubernetes.io/name: rhbk-operator
    app.kubernetes.io/managed-by: kustomize
    realm.stakater.com/realm-import-sample: "true"
  name: keycloak-restore
spec:
  instances: 2
  admin:
    username:
      secret:
        name: admin
        key: username
    password:
      secret:
        name: admin
        key: password
  database:
    host:
      secret:
        name: cpg-cluster-app
        key: host
    port:
      secret:
        name: cpg-cluster-app
        key: port
    user:
      secret:
        name: cpg-cluster-app
        key: user
    password:
      secret:
        name: cpg-cluster-app
        key: password
#  providers:
#    - name: keycloak-metrics-spi-6.0.0.jar
#      url:
#        secret:
#          name: custom-spi
#          key: metrics-spi