apiVersion: sso.stakater.com/v1alpha1
kind: Keycloak
metadata:
  labels:
    app.kubernetes.io/name: rhbk-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloak-sample
spec:
  instances: 1
  admin:
    username:
      secret:
        name: admin
        key: username
    password:
      secret:
        name: admin
        key: password
  database:
    name:
      secret:
        name: plankton-cluster-pguser-rhbk
        key: dbname
    host:
      secret:
        name: plankton-cluster-pguser-rhbk
        key: host
    port:
      secret:
        name: plankton-cluster-pguser-rhbk
        key: port
    user:
      secret:
        name: plankton-cluster-pguser-rhbk
        key: user
    password:
      secret:
        name: plankton-cluster-pguser-rhbk
        key: password
  providers:
    - name: keycloak-metrics-spi-6.0.0.jar
      url:
        secret:
          name: custom-spi
          key: metrics-spi
